#!/usr/bin/env node
/**
 * Step 2: Send a proof to the verifier contract for on-chain verification.
 *
 * Reads proof from .test-tmp/verify-input.json (generated by gen-proof.cjs)
 *
 * Usage: node scripts/verify-onchain.cjs
 */

const { rpc, TransactionBuilder, BASE_FEE, Contract, Address, nativeToScVal, xdr, Keypair } = require('@stellar/stellar-sdk')
const { readFileSync } = require('fs')
const { resolve } = require('path')

const FRONTEND = resolve(__dirname, '..')

function loadEnv() {
  const envPath = resolve(FRONTEND, '.env')
  const env = {}
  const content = readFileSync(envPath, 'utf-8')
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eqIdx = trimmed.indexOf('=')
    if (eqIdx === -1) continue
    env[trimmed.slice(0, eqIdx).trim()] = trimmed.slice(eqIdx + 1).trim()
  }
  return env
}

const env = loadEnv()
const RPC_URL = env.VITE_RPC_URL || 'https://soroban-testnet.stellar.org'
const NETWORK = env.VITE_NETWORK_PASSPHRASE || 'Test SDF Network ; September 2015'
const VERIFIER_ID = env.VITE_CONTRACT_VERIFIER
const SECRET = env.STELLAR_SECRET

// ─── Hex helpers ──────────────────────────────────────────────────────────────

function bytesVal(hex, byteLen = 32) {
  return xdr.ScVal.scvBytes(Buffer.from(hex, 'hex'))
}

function vecBytesVal(hexArr) {
  return xdr.ScVal.scvVec(hexArr.map(h => bytesVal(h, 32)))
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const proofPath = resolve(FRONTEND, '.test-tmp', 'verify-input.json')
  let proof
  try {
    proof = JSON.parse(readFileSync(proofPath, 'utf8'))
  } catch {
    console.error('Proof not found at', proofPath)
    console.error('Run gen-proof.cjs first')
    process.exit(1)
  }

  console.log('Proof loaded:')
  console.log('  proofA:', proof.proofA.slice(0, 20) + '...')
  console.log('  proofB:', proof.proofB.slice(0, 20) + '...')
  console.log('  proofC:', proof.proofC.slice(0, 20) + '...')
  console.log('  publicInputs:', proof.publicInputs.length, 'signals')

  const kp = Keypair.fromSecret(SECRET)
  const source = kp.publicKey()
  console.log('Source:', source)
  console.log('Verifier:', VERIFIER_ID)

  const rpcClient = new rpc.Server(RPC_URL)
  const contract = new Contract(VERIFIER_ID)

  // Simulate verify call (no tx cost for read-only simulation)
  const account = await rpcClient.getAccount(source)
  const op = contract.call('verify',
    bytesVal(proof.proofA, 64),
    bytesVal(proof.proofB, 128),
    bytesVal(proof.proofC, 64),
    vecBytesVal(proof.publicInputs),
  )

  const baseTx = new TransactionBuilder(account, {
    fee: BASE_FEE, networkPassphrase: NETWORK,
  }).addOperation(op).setTimeout(60).build()

  console.log('\nSimulating verify...')
  const sim = await rpcClient.simulateTransaction(baseTx)

  if (rpc.Api.isSimulationError(sim)) {
    console.error('❌ Simulation error:', sim.error)
    return
  }

  const result = sim.result.retval
  const verified = result.value()
  console.log(verified ? '✅ PROOF IS VALID ON-CHAIN' : '❌ PROOF IS INVALID')
  console.log('')
  if (verified) {
    console.log('The full pipeline is working:')
    console.log('  1. WASM + zkey = proof generation ✓')
    console.log('  2. Verifier vkey = proof verification on-chain ✓')
    console.log('  3. Withdrawals should now succeed through the frontend')
  } else {
    console.log('The verifier rejected the proof. Possible causes:')
    console.log('  - vkey mismatch between zkey and on-chain verifier')
    console.log('  - Public inputs don\'t match circuit expectations')
    console.log('  - Proof encoding is wrong')
  }
}

main().catch(e => {
  console.error(e)
  process.exit(1)
})
